name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1  
      - name: Build
        run: | 
          npm install
          npm run build --production
      - name: Save commit message into file
        run: |
          echo  ${{ github.event.head_commit.message }}  >>${{ format('./dist/commit_message', steps.package-version.outputs.current-version ) }}
      - name: Upload via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_LOGIN }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: "./dist/"
          remote_dir: ${{ format('./{0}/', steps.package-version.outputs.current-version ) }}
          delete: "true"
      