name: Deploy

on:
  # Trigger only on tag push events with tags that start with "v"
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Get npm version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1  

      - name: Build
        run: | 
          npm install
          npm run build --production

      - name: Extract version from tag and save message
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: |
          VERSION=${TAG_NAME#v} # Remove the leading 'v' from the tag
          # Get the tag message (annotation) if it exists, otherwise use commit message
          if git tag -l "$TAG_NAME" | grep -q .; then
            TAG_MESSAGE=$(git tag -l --format='%(contents:subject)' "$TAG_NAME")
            if [ -z "$TAG_MESSAGE" ]; then
              TAG_MESSAGE=$(git tag -l --format='%(contents)' "$TAG_NAME")
            fi
          else
            TAG_MESSAGE="${{ github.event.head_commit.message }}"
          fi
          echo "${TAG_MESSAGE}" > "./dist/message"

      - name: FTP Deploy & Remote PHP Unzip
        uses: zdenecek/zip-ftp-php-unzip@v1.0.0
        with:
          zip_source: "public/*"
          ftp_host: ${{ secrets.FTP_SERVER }}
          ftp_user: ${{ secrets.FTP_LOGIN }}
          ftp_password: ${{ secrets.FTP_PASSWORD }}
          ftp_remote_path: "./${{ github.ref_name }}/"
          php_script_url: "https://bp.zdenektomis.eu/${{ github.ref_name }}" 
