name: Deploy

on:
  # Trigger only on tag push events with tags that start with "v"
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Extract the version from the tag (without the "v" prefix)
      - name: Extract version from tag
        id: tag-version
        run: echo "tag=${GITHUB_REF##*/}" | sed 's/^v//' > version.txt
      - name: Get tag version
        id: package-version
        run: echo "::set-output name=current-version::$(cat version.txt)"

      # Get the tag message
      - name: Get tag message
        id: tag-message
        run: |
          TAG_MESSAGE=$(git for-each-ref --format='%(contents)' "refs/tags/${GITHUB_REF##*/}")
          echo "::set-output name=message::$TAG_MESSAGE"

      - name: Build
        run: | 
          npm install
          npm run build --production

      - name: Save tag message into file
        run: |
          echo "${{ steps.tag-message.outputs.message }}" >> "./dist/tag_message_${{ steps.tag-version.outputs.current-version }}"

      - name: Upload via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_LOGIN }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: "./dist/"
          remote_dir: ${{ format('./{0}/', steps.tag-version.outputs.current-version) }}
          delete: "true"
